// BRBR Community — 50 Mock Member Profiles
// African American Women across all 5 BRBR cities
// Avatar URLs use ui-avatars.com with BRBR brand colors

function avatarUrl(name) {
  return `https://ui-avatars.com/api/?name=${encodeURIComponent(name)}&background=C9A688&color=0A0A0A&bold=true&size=128&font-size=0.4`;
}

export const MOCK_MEMBERS = [
  // ─── BATON ROUGE (10) ───
  { id: 1,  name: 'Nikki Thompson',    avatar: avatarUrl('Nikki Thompson'),    initials: 'NT', work: 'Licensed Counselor',        location: 'Baton Rouge',  bio: 'Dedicated mental health advocate helping families navigate healing and wholeness through faith-based counseling.',               currentGroups: ['Healing Through Words', 'Faith Foundations'] },
  { id: 2,  name: 'Sierra Williams',   avatar: avatarUrl('Sierra Williams'),   initials: 'SW', work: 'Elementary Teacher',        location: 'Baton Rouge',  bio: 'Passionate educator inspiring young minds in underserved communities through literacy and creative expression.',                 currentGroups: ['Faith Foundations', 'Growth Mindset'] },
  { id: 3,  name: 'Jasmine Carter',    avatar: avatarUrl('Jasmine Carter'),    initials: 'JC', work: 'Youth Mentor',              location: 'Baton Rouge',  bio: 'Empowering at-risk youth through mentorship, life skills workshops, and community engagement programs.',                        currentGroups: ['Sister Circle', 'Purpose & Prayer'] },
  { id: 4,  name: 'Destiny Brooks',    avatar: avatarUrl('Destiny Brooks'),    initials: 'DB', work: 'Social Worker',             location: 'Baton Rouge',  bio: 'Committed to strengthening families through wraparound services and community-based advocacy.',                                 currentGroups: ['Healing Through Words', 'Sister Circle'] },
  { id: 5,  name: 'Aaliyah Washington',avatar: avatarUrl('Aaliyah Washington'),initials: 'AW', work: 'Nurse Practitioner',        location: 'Baton Rouge',  bio: 'Providing compassionate healthcare to underserved populations with a focus on maternal and child wellness.',                     currentGroups: ['Growth Mindset', 'Purpose & Prayer'] },
  { id: 6,  name: 'Imani Davis',       avatar: avatarUrl('Imani Davis'),       initials: 'ID', work: 'Church Administrator',      location: 'Baton Rouge',  bio: 'Organizing faith communities to serve their neighborhoods through outreach and spiritual development.',                         currentGroups: ['Faith Foundations', 'Purpose & Prayer'] },
  { id: 7,  name: 'Kayla Robinson',    avatar: avatarUrl('Kayla Robinson'),    initials: 'KR', work: 'Hair Stylist & Entrepreneur', location: 'Baton Rouge',bio: 'Building a beauty empire while mentoring young women in business ownership and financial literacy.',                             currentGroups: ['Growth Mindset', 'Sister Circle'] },
  { id: 8,  name: 'Tiana Mitchell',    avatar: avatarUrl('Tiana Mitchell'),    initials: 'TM', work: 'Paralegal',                 location: 'Baton Rouge',  bio: 'Advocating for justice and equity through legal support services for families in need.',                                        currentGroups: ['Healing Through Words', 'Growth Mindset'] },
  { id: 9,  name: 'Brianna Jackson',   avatar: avatarUrl('Brianna Jackson'),   initials: 'BJ', work: 'Fitness Coach',             location: 'Baton Rouge',  bio: 'Transforming lives through holistic wellness, mind-body fitness, and community health initiatives.',                            currentGroups: ['Sister Circle', 'Growth Mindset'] },
  { id: 10, name: 'Zaria Coleman',     avatar: avatarUrl('Zaria Coleman'),     initials: 'ZC', work: 'Graphic Designer',          location: 'Baton Rouge',  bio: 'Creating visual stories that celebrate Black culture, faith, and community resilience.',                                        currentGroups: ['Healing Through Words', 'Purpose & Prayer'] },

  // ─── HOUSTON (10) ───
  { id: 11, name: 'Tamara Harris',     avatar: avatarUrl('Tamara Harris'),     initials: 'TH', work: 'Pastor',                    location: 'Houston',      bio: 'Leading a vibrant congregation with a heart for community service and family restoration.',                                     currentGroups: ['Faith Foundations', 'Purpose & Prayer'] },
  { id: 12, name: 'Monique Taylor',    avatar: avatarUrl('Monique Taylor'),    initials: 'MT', work: 'Real Estate Agent',         location: 'Houston',      bio: 'Helping families achieve homeownership dreams while building generational wealth in Black communities.',                        currentGroups: ['Growth Mindset', 'Sister Circle'] },
  { id: 13, name: 'Crystal Jones',     avatar: avatarUrl('Crystal Jones'),     initials: 'CJ', work: 'School Counselor',          location: 'Houston',      bio: 'Guiding students through academic and personal challenges with culturally responsive counseling.',                              currentGroups: ['Healing Through Words', 'Faith Foundations'] },
  { id: 14, name: 'Ebony Anderson',    avatar: avatarUrl('Ebony Anderson'),    initials: 'EA', work: 'Program Director',          location: 'Houston',      bio: 'Designing community programs that address food insecurity, education, and workforce readiness.',                                currentGroups: ['Growth Mindset', 'Purpose & Prayer'] },
  { id: 15, name: 'Shanice Brown',     avatar: avatarUrl('Shanice Brown'),     initials: 'SB', work: 'Registered Nurse',          location: 'Houston',      bio: 'Serving on the frontlines of community health with compassion, skill, and unwavering dedication.',                              currentGroups: ['Sister Circle', 'Healing Through Words'] },
  { id: 16, name: 'Latoya Green',      avatar: avatarUrl('Latoya Green'),      initials: 'LG', work: 'Attorney',                  location: 'Houston',      bio: 'Fighting for civil rights and equitable access to justice for marginalized families.',                                          currentGroups: ['Faith Foundations', 'Growth Mindset'] },
  { id: 17, name: 'Deja White',        avatar: avatarUrl('Deja White'),        initials: 'DW', work: 'Event Coordinator',         location: 'Houston',      bio: 'Bringing communities together through celebrations, fundraisers, and cultural events.',                                         currentGroups: ['Sister Circle', 'Purpose & Prayer'] },
  { id: 18, name: 'Keisha Martin',     avatar: avatarUrl('Keisha Martin'),     initials: 'KM', work: 'Pharmacist',                location: 'Houston',      bio: 'Ensuring medication access and health education in underserved neighborhoods.',                                                 currentGroups: ['Healing Through Words', 'Growth Mindset'] },
  { id: 19, name: 'Nia Lewis',         avatar: avatarUrl('Nia Lewis'),         initials: 'NL', work: 'Journalist',                location: 'Houston',      bio: 'Amplifying Black voices and community stories through investigative journalism and storytelling.',                              currentGroups: ['Healing Through Words', 'Faith Foundations'] },
  { id: 20, name: 'Janae Clark',       avatar: avatarUrl('Janae Clark'),       initials: 'JC', work: 'Dance Instructor',          location: 'Houston',      bio: 'Teaching self-expression, discipline, and cultural pride through movement and dance.',                                          currentGroups: ['Sister Circle', 'Growth Mindset'] },

  // ─── ATLANTA (10) ───
  { id: 21, name: 'Alana Scott',       avatar: avatarUrl('Alana Scott'),       initials: 'AS', work: 'Marketing Director',        location: 'Atlanta',      bio: 'Building brand strategies that elevate Black-owned businesses and community organizations.',                                    currentGroups: ['Growth Mindset', 'Sister Circle'] },
  { id: 22, name: 'Renee Walker',      avatar: avatarUrl('Renee Walker'),      initials: 'RW', work: 'Clinical Psychologist',     location: 'Atlanta',      bio: 'Providing culturally affirming therapy focused on trauma recovery and emotional well-being.',                                    currentGroups: ['Healing Through Words', 'Purpose & Prayer'] },
  { id: 23, name: 'Chanel Moore',      avatar: avatarUrl('Chanel Moore'),      initials: 'CM', work: 'Music Producer',            location: 'Atlanta',      bio: 'Creating inspirational music that blends gospel, R&B, and spoken word to uplift communities.',                                  currentGroups: ['Faith Foundations', 'Healing Through Words'] },
  { id: 24, name: 'Essence Thomas',    avatar: avatarUrl('Essence Thomas'),    initials: 'ET', work: 'Nonprofit Founder',         location: 'Atlanta',      bio: 'Founded a grassroots organization providing after-school programs and summer camps for youth.',                                  currentGroups: ['Purpose & Prayer', 'Growth Mindset'] },
  { id: 25, name: 'Naomi Jackson',     avatar: avatarUrl('Naomi Jackson'),     initials: 'NJ', work: 'Professor',                 location: 'Atlanta',      bio: 'Teaching African American history and literature while mentoring the next generation of scholars.',                              currentGroups: ['Healing Through Words', 'Faith Foundations'] },
  { id: 26, name: 'Savannah Hill',     avatar: avatarUrl('Savannah Hill'),     initials: 'SH', work: 'Occupational Therapist',    location: 'Atlanta',      bio: 'Helping individuals regain independence and confidence through personalized rehabilitation programs.',                           currentGroups: ['Sister Circle', 'Growth Mindset'] },
  { id: 27, name: 'Lyric Adams',       avatar: avatarUrl('Lyric Adams'),       initials: 'LA', work: 'Pediatrician',              location: 'Atlanta',      bio: 'Ensuring every child has access to quality healthcare regardless of their zip code.',                                           currentGroups: ['Faith Foundations', 'Purpose & Prayer'] },
  { id: 28, name: 'Harmony Wright',    avatar: avatarUrl('Harmony Wright'),    initials: 'HW', work: 'Interior Designer',         location: 'Atlanta',      bio: 'Transforming living spaces into sanctuaries that reflect cultural heritage and personal growth.',                                currentGroups: ['Growth Mindset', 'Sister Circle'] },
  { id: 29, name: 'Zoe Campbell',      avatar: avatarUrl('Zoe Campbell'),      initials: 'ZC', work: 'Financial Advisor',         location: 'Atlanta',      bio: 'Empowering families with financial literacy, investment strategies, and wealth-building plans.',                                 currentGroups: ['Growth Mindset', 'Purpose & Prayer'] },
  { id: 30, name: 'Serena Phillips',   avatar: avatarUrl('Serena Phillips'),   initials: 'SP', work: 'Life Coach',                location: 'Atlanta',      bio: 'Guiding women through personal transformation with tools rooted in faith and self-discovery.',                                  currentGroups: ['Healing Through Words', 'Sister Circle'] },

  // ─── DALLAS (10) ───
  { id: 31, name: 'Maya Patterson',    avatar: avatarUrl('Maya Patterson'),    initials: 'MP', work: 'Software Engineer',         location: 'Dallas',       bio: 'Breaking barriers in tech while mentoring young women of color in STEM careers.',                                               currentGroups: ['Growth Mindset', 'Sister Circle'] },
  { id: 32, name: 'Autumn Reed',       avatar: avatarUrl('Autumn Reed'),       initials: 'AR', work: 'Doula & Midwife',           location: 'Dallas',       bio: 'Supporting Black mothers through pregnancy, birth, and postpartum with holistic and culturally informed care.',                  currentGroups: ['Healing Through Words', 'Purpose & Prayer'] },
  { id: 33, name: 'Trinity Howard',    avatar: avatarUrl('Trinity Howard'),    initials: 'TH', work: 'High School Principal',     location: 'Dallas',       bio: 'Leading educational transformation and creating safe learning environments for students of all backgrounds.',                    currentGroups: ['Faith Foundations', 'Growth Mindset'] },
  { id: 34, name: 'Jade Cooper',       avatar: avatarUrl('Jade Cooper'),       initials: 'JC', work: 'Chef & Restaurateur',       location: 'Dallas',       bio: 'Celebrating Southern Black culinary traditions while building a restaurant that nourishes body and soul.',                       currentGroups: ['Sister Circle', 'Healing Through Words'] },
  { id: 35, name: 'Kennedy Ross',      avatar: avatarUrl('Kennedy Ross'),      initials: 'KR', work: 'Photographer',              location: 'Dallas',       bio: 'Capturing the beauty, strength, and joy of Black women and families through portrait and event photography.',                    currentGroups: ['Growth Mindset', 'Purpose & Prayer'] },
  { id: 36, name: 'London Bailey',     avatar: avatarUrl('London Bailey'),     initials: 'LB', work: 'Dental Hygienist',          location: 'Dallas',       bio: 'Promoting oral health awareness in communities that lack access to preventive dental care.',                                     currentGroups: ['Faith Foundations', 'Sister Circle'] },
  { id: 37, name: 'Peyton Sanders',    avatar: avatarUrl('Peyton Sanders'),    initials: 'PS', work: 'Social Media Strategist',   location: 'Dallas',       bio: 'Helping nonprofits and small businesses amplify their mission through digital storytelling.',                                    currentGroups: ['Growth Mindset', 'Healing Through Words'] },
  { id: 38, name: 'Aria Morgan',       avatar: avatarUrl('Aria Morgan'),       initials: 'AM', work: 'Worship Leader',            location: 'Dallas',       bio: 'Leading congregations in praise and spiritual growth through music, prayer, and fellowship.',                                   currentGroups: ['Faith Foundations', 'Purpose & Prayer'] },
  { id: 39, name: 'Chloe Foster',      avatar: avatarUrl('Chloe Foster'),      initials: 'CF', work: 'Accountant',                location: 'Dallas',       bio: 'Providing financial management and tax services to help families and small businesses thrive.',                                  currentGroups: ['Growth Mindset', 'Sister Circle'] },
  { id: 40, name: 'Reign Butler',      avatar: avatarUrl('Reign Butler'),      initials: 'RB', work: 'Yoga Instructor',           location: 'Dallas',       bio: 'Creating healing spaces through yoga, meditation, and mindfulness rooted in Black wellness traditions.',                         currentGroups: ['Healing Through Words', 'Purpose & Prayer'] },

  // ─── NEW ORLEANS (10) ───
  { id: 41, name: 'Gloria Jean Baptiste', avatar: avatarUrl('Gloria Baptiste'),initials: 'GB', work: 'Community Organizer',       location: 'New Orleans',  bio: 'Mobilizing grassroots movements for housing justice and equitable rebuilding in post-Katrina neighborhoods.',                    currentGroups: ['Purpose & Prayer', 'Sister Circle'] },
  { id: 42, name: 'Amara Thibodaux',   avatar: avatarUrl('Amara Thibodaux'),   initials: 'AT', work: 'Midwife',                   location: 'New Orleans',  bio: 'Combining traditional birthing wisdom with modern medicine to support Black maternal health.',                                   currentGroups: ['Healing Through Words', 'Faith Foundations'] },
  { id: 43, name: 'Soleil Fontenot',   avatar: avatarUrl('Soleil Fontenot'),   initials: 'SF', work: 'Jazz Vocalist',             location: 'New Orleans',  bio: 'Preserving the rich musical heritage of New Orleans while inspiring a new generation of performers.',                           currentGroups: ['Sister Circle', 'Healing Through Words'] },
  { id: 44, name: 'Camille Broussard', avatar: avatarUrl('Camille Broussard'), initials: 'CB', work: 'Elementary Principal',      location: 'New Orleans',  bio: 'Transforming school culture through culturally responsive teaching and community-driven leadership.',                            currentGroups: ['Faith Foundations', 'Growth Mindset'] },
  { id: 45, name: 'Nadia Landry',      avatar: avatarUrl('Nadia Landry'),      initials: 'NL', work: 'Public Health Director',    location: 'New Orleans',  bio: 'Leading city-wide health initiatives focused on maternal health, nutrition, and preventive care.',                               currentGroups: ['Purpose & Prayer', 'Growth Mindset'] },
  { id: 46, name: 'Raven Duval',       avatar: avatarUrl('Raven Duval'),       initials: 'RD', work: 'Artist & Muralist',         location: 'New Orleans',  bio: 'Painting vibrant murals that tell the stories of resilience, culture, and beauty in Black communities.',                         currentGroups: ['Healing Through Words', 'Sister Circle'] },
  { id: 47, name: 'Celeste Arceneaux', avatar: avatarUrl('Celeste Arceneaux'), initials: 'CA', work: 'Family Therapist',          location: 'New Orleans',  bio: 'Helping families rebuild trust, communication, and connection through culturally grounded therapy.',                             currentGroups: ['Healing Through Words', 'Purpose & Prayer'] },
  { id: 48, name: 'Jolie Mouton',      avatar: avatarUrl('Jolie Mouton'),      initials: 'JM', work: 'Librarian',                 location: 'New Orleans',  bio: 'Curating collections and programs that center Black authors, history, and community literacy.',                                  currentGroups: ['Faith Foundations', 'Healing Through Words'] },
  { id: 49, name: 'Marguerite Pierre',  avatar: avatarUrl('Marguerite Pierre'), initials: 'MP', work: 'Caterer & Baker',          location: 'New Orleans',  bio: 'Honoring Creole culinary traditions while building a catering business that feeds the community.',                               currentGroups: ['Sister Circle', 'Growth Mindset'] },
  { id: 50, name: 'Treasure Simmons',  avatar: avatarUrl('Treasure Simmons'),  initials: 'TS', work: 'Nonprofit Director',        location: 'New Orleans',  bio: 'Running a nonprofit that provides housing, job training, and mentorship for formerly incarcerated women.',                       currentGroups: ['Purpose & Prayer', 'Faith Foundations'] },
];

export const READING_GROUPS_LIST = [
  'Healing Through Words',
  'Faith Foundations',
  'Growth Mindset',
  'Sister Circle',
  'Purpose & Prayer',
];

export default MOCK_MEMBERS;